services:
  - type: web
    name: acne-detector
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools==75.8.0 wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10